import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Blog App | GU",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="shortcut icon" href="/logo.svg" type="image/x-icon" />
        </head>
        <body className={outfit.className}>{children}</body>
      </html>
    // </ClerkProvider>
  );
}
